Develop
mararosa/signin-signup pull request #1
Opened 2022-04-08 01:11 UTC by mararosa

### Login module

- Login Screen
- Email and password validation
- Login Request
- Unit Tests

2022-04-12 08:52 UTC, felipejm requested changes
Booooa Mara.. Parabéns!!!

O código ta muito bem implementado e seguindo os padrões certinhos.
Deixei alguns comentarios apenas para voce nao me xingar dizendo que nao comentei nada :) hahaha.

2022-04-12 08:52 UTC, felipejm commented on app/src/main/java/com/estudos/signupsignin/signin/view/SignInActivity.kt
> +    val textWatcher = object : TextWatcher {
Essa variável poderia ser privada ou até mesmo poderia estar em outra classe para nao deixar a activity muito complexa.

2022-04-12 08:52 UTC, felipejm commented on app/src/main/java/com/estudos/signupsignin/signin/view/SignInActivity.kt
> +            password = binding.inputPassword.text.toString()
Seria bom não salvar o email e password como variável na activity, pois como a activity tem o seu ciclo de vida, ela pode ser criada, recriada, destruída, etc.. essa informação pode ficar inconsistente.

é melhor pegar essa info só quando precisar.

2022-04-12 08:52 UTC, felipejm commented on app/src/main/java/com/estudos/signupsignin/signin/viewmodel/SignInViewModel.kt
> +    val interactor: SignInInteractor,
essas variáveis podem ser private ?

2022-04-12 08:52 UTC, felipejm commented on app/src/test/java/com/estudos/signupsignin/viewmodel/SignInViewModelTest.kt
> +    fun givenInputValues_whenEmailIsInvalid_thenSendCommandFalseAndMessageError() {
acho que faltou testar o cenário de password com menos de 8 caracteres.

2022-05-05 02:14 UTC, mararosa commented on app/src/main/java/com/estudos/signupsignin/signin/view/SignInActivity.kt
> +            password = binding.inputPassword.text.toString()
Ajustado

2022-05-05 03:42 UTC, merged